name: Build and Test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '3.1.x'
      - name: Restore dependencies
        run: dotnet restore PasswordManager.sln
      - name: Build
        run: dotnet build PasswordManager.sln --no-restore
      - name: Test
        run: dotnet test PasswordManager.sln --no-build --verbosity normal
